twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: 
        - 'bootstrap_5_layout.html.twig'
    globals:
        category: '@App\Repository\CategoryRepository'

# Optional configuration for when running tests
when@test:
    twig:
        strict_variables: true
